# Generated by Django 5.2.15 on 2026-07-13 08:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Dormitory Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dormitory',
                'verbose_name_plural': 'Dormitories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('capacity', models.SmallIntegerField(help_text='Maximum number of residents allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_rent', models.PositiveIntegerField(default=0, help_text='Monthly rent amount in local currency')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory.dormitory')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['dormitory', 'room_number'],
                'unique_together': {('dormitory', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(help_text='National identification number', max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('parent_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('entry_date', models.DateField(help_text='Date when resident moved in')),
                ('exit_date', models.DateField(blank=True, help_text='Date when resident moved out (if applicable)', null=True)),
                ('monthly_payment_day', models.IntegerField(default=1, help_text='Day of month when recurring payment is due (1-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LEFT', 'Left')], default='ACTIVE', max_length=10)),
                ('id_card_image', models.ImageField(blank=True, help_text='Scanned copy of ID card', null=True, upload_to='id_cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='dormitory.dormitory')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_residents', to='accounts.supervisor')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='dormitory.room')),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'ordering': ['dormitory', 'room', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Transaction amount in local currency', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('RENT', 'Monthly Rent'), ('DEPOSIT', 'Security Deposit'), ('OTHER', 'Other Payment')], max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card Payment'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE_GATEWAY', 'Online Gateway')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional notes about the transaction')),
                ('payment_date', models.DateTimeField(help_text='When the payment was actually made')),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference or receipt number (optional)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to='accounts.supervisor')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='dormitory.dormitory')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='dormitory.resident')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-payment_date'],
            },
        ),
    ]
