# Generated by Django 5.2.15 on 2026-07-13 08:44

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='entry_date',
            field=django_jalali.db.models.jDateField(help_text='Date when resident moved in'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='exit_date',
            field=django_jalali.db.models.jDateField(blank=True, help_text='Date when resident moved out (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_date',
            field=django_jalali.db.models.jDateTimeField(help_text='When the payment was actually made'),
        ),
    ]
