# Generated by Django 5.2.15 on 2026-07-25 21:06

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_alter_resident_entry_date_alter_resident_exit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='occupation',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('EMPLOYED', 'Employed'), ('OTHER', 'Other')], default='STUDENT', help_text='Resident occupation type', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the payment has been approved by supervisor (required for CASH and CARD)'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveBigIntegerField(help_text='Amount in Rials (automatically converted from Tomans)'),
        ),
    ]
