# Generated by Django 5.2.15 on 2026-07-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_resident_occupation_transaction_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='monthly_rent',
            field=models.PositiveBigIntegerField(default=0, help_text='Monthly rent in Rials (automatically converted from Tomans)'),
        ),
    ]
