# Generated by Django 5.2.15 on 2026-07-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0004_alter_room_monthly_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='applicable_rent',
            field=models.PositiveBigIntegerField(blank=True, help_text='Room rent at the time of this transaction (in Rials). Only for RENT type.', null=True),
        ),
    ]
