# Generated by Django 5.2.15 on 2026-07-26 05:44

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_transaction_applicable_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='settled_until',
            field=django_jalali.db.models.jDateField(blank=True, help_text='Date until which the resident has fully paid', null=True),
        ),
    ]
