# Generated by Django 5.2.15 on 2026-07-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0006_resident_settled_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='parent_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('RENT', 'Monthly Rent'), ('DEPOSIT', 'Deposit')], max_length=20),
        ),
    ]
