# Generated by Django 5.2.15 on 2026-09-23 13:09

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0007_alter_resident_parent_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='period_end',
            field=django_jalali.db.models.jDateField(blank=True, help_text='End date of rent period covered (Jalali)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='period_name',
            field=models.CharField(blank=True, help_text='Persian name of the covered month/period (e.g. اجاره مهر ماه ۱۴۰۵)', max_length=150),
        ),
        migrations.AddField(
            model_name='transaction',
            name='period_start',
            field=django_jalali.db.models.jDateField(blank=True, help_text='Start date of rent period covered (Jalali)', null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='settled_until',
            field=django_jalali.db.models.jDateField(blank=True, help_text='Date until which the resident has fully paid (pre-paid coverage end date)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the payment has been approved by supervisor (required for CASH and BANK_TRANSFER)'),
        ),
    ]
