# Generated by Django 5.2.15 on 2026-09-23 13:25

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dormitory', '0008_transaction_period_end_transaction_period_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(default=jdatetime.date.today, help_text='تاریخ ثبت یادداشت')),
                ('title', models.CharField(help_text='عنوان یادداشت یا مشکل', max_length=255)),
                ('content', models.TextField(help_text='شرح کامل گزارش یا یادداشت')),
                ('note_type', models.CharField(choices=[('MAINTENANCE', 'تعمیرات و تاسیسات'), ('DISCIPLINARY', 'انضباطی'), ('CLEANING', 'نظافت'), ('GENERAL', 'عمومی و اداری')], default='GENERAL', max_length=20)),
                ('is_resolved', models.BooleanField(default=False, help_text='آیا موضوع رسیدگی و برطرف شده است؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_notes', to='accounts.supervisor')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to='dormitory.dormitory')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_notes', to='dormitory.resident')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_notes', to='dormitory.room')),
            ],
            options={
                'verbose_name': 'Daily Note',
                'verbose_name_plural': 'Daily Notes',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
