# Generated by Django 5.2.15 on 2026-09-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0009_dailynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='national_code',
            field=models.CharField(blank=True, help_text='National identification number (optional at registration if pending)', max_length=10, null=True, unique=True),
        ),
    ]
