# Generated by Django 5.2.15 on 2026-09-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0010_alter_resident_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_foreign',
            field=models.BooleanField(default=False, help_text='در صورت علامت زدن، فیلد شناسه به عنوان شماره پاسپورت یا کد فراگیر اتباع ثبت می\u200cشود.', verbose_name='تبعه خارجی (اتباع)'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='national_code',
            field=models.CharField(blank=True, help_text='کد ملی ۱۰ رقمی (ایرانی) یا شماره پاسپورت / کد فراگیر (اتباع). در صورت عدم دسترسی، خالی بگذارید.', max_length=30, null=True, unique=True, verbose_name='کد ملی / شماره پاسپورت'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='parent_phone_number',
            field=models.CharField(blank=True, help_text="شماره تماس والدین یا بستگان درجه یک. در صورت عدم دسترسی، خالی یا 'ندارد' بگذارید.", max_length=11, null=True, verbose_name='شماره تماس والدین'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تماس ساکن'),
        ),
    ]
