# Generated by Django 5.2.15 on 2026-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0011_resident_is_foreign_alter_resident_national_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='father_name',
            field=models.CharField(blank=True, help_text='نام پدر ساکن. در صورت عدم دسترسی، خالی بگذارید (جزو کسری مدارک محسوب می\u200cشود).', max_length=255, null=True, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='resident',
            name='has_deposit',
            field=models.BooleanField(default=False, help_text='مشخص می\u200cکند که آیا ودیعه از ساکن دریافت شده است یا خیر.', verbose_name='ودیعه دارد'),
        ),
        migrations.AddField(
            model_name='resident',
            name='has_lease',
            field=models.BooleanField(default=False, help_text='مشخص می\u200cکند که آیا اجاره\u200cنامه رسمی با ساکن منعقد/تحویل شده است یا خیر.', verbose_name='اجاره\u200cنامه دارد'),
        ),
    ]
