# Generated by Django 5.2.15 on 2026-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0012_resident_father_name_resident_has_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='id_card_image_2',
            field=models.ImageField(blank=True, help_text='تصویر پشت کارت ملی یا صفحه دوم پاسپورت (اختیاری - فشرده\u200cسازی خودکار).', null=True, upload_to='id_cards/', verbose_name='تصویر مدارک شناسایی (۲)'),
        ),
        migrations.AddField(
            model_name='resident',
            name='id_card_image_3',
            field=models.ImageField(blank=True, help_text='تصویر شناسنامه یا سایر مدارک هویتی (اختیاری - فشرده\u200cسازی خودکار).', null=True, upload_to='id_cards/', verbose_name='تصویر مدارک شناسایی (۳)'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='id_card_image',
            field=models.ImageField(blank=True, help_text='تصویر روی کارت ملی یا صفحه اول پاسپورت (فشرده\u200cسازی خودکار تا زیر ۱ مگابایت).', null=True, upload_to='id_cards/', verbose_name='تصویر مدارک شناسایی (۱)'),
        ),
    ]
