# Generated by Django 5.2.15 on 2026-09-25 12:59

import apps.dormitory.models.daily_note
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0013_resident_id_card_image_2_resident_id_card_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynote',
            name='date',
            field=django_jalali.db.models.jDateField(default=apps.dormitory.models.daily_note.get_yesterday_jalali, help_text='تاریخ ثبت یادداشت'),
        ),
    ]
