# Generated by Django 5.2.15 on 2026-09-25 15:09

import apps.dormitory.models.dormitory
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0014_alter_dailynote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynote',
            name='dormitory',
            field=models.ForeignKey(default=apps.dormitory.models.dormitory.get_default_dormitory, on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to='dormitory.dormitory'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='dormitory',
            field=models.ForeignKey(default=apps.dormitory.models.dormitory.get_default_dormitory, on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='dormitory.dormitory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='dormitory',
            field=models.ForeignKey(default=apps.dormitory.models.dormitory.get_default_dormitory, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory.dormitory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dormitory',
            field=models.ForeignKey(default=apps.dormitory.models.dormitory.get_default_dormitory, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='dormitory.dormitory'),
        ),
    ]
