# Generated by Django 5.2.15 on 2026-09-25 15:13

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dormitory', '0015_alter_dailynote_dormitory_alter_resident_dormitory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.PositiveBigIntegerField(help_text='مبلغ اجاره به ریال', verbose_name='اجاره ماهانه (ریال)')),
                ('effective_date', django_jalali.db.models.jDateField(help_text='تاریخی که این نرخ از آن تاریخ به بعد اعمال می\u200cشود', verbose_name='تاریخ شروع اعمال نرخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت تغییر')),
                ('note', models.CharField(blank=True, default='', help_text='علت تغییر نرخ (مثلاً افزایش قیمت پاییز ۱۴۰۵)', max_length=255, verbose_name='توضیحات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.supervisor', verbose_name='ثبت\u200cکننده')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='dormitory.room', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'تاریخچه نرخ اتاق',
                'verbose_name_plural': 'تاریخچه نرخ\u200cهای اتاق',
                'ordering': ['-effective_date', '-id'],
                'unique_together': {('room', 'effective_date')},
            },
        ),
    ]
