# Generated by Django 5.2.15 on 2026-09-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0016_roompricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, help_text='مبلغ کسر شده از اجاره مصوب به دلیل سم\u200cپاشی، تخلیه موقت یا توافق مدیریت', verbose_name='مبلغ کسورات / تخفیف استثنایی (ریال)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_reason',
            field=models.CharField(blank=True, default='', help_text='مثال: سم\u200cپاشی خوابگاه و ۵ روز تخلیه موقت اتاق', max_length=255, verbose_name='علت و جزئیات کسورات'),
        ),
    ]
