# Generated by Django 5.2.15 on 2026-09-26 15:39

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0017_transaction_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='settled_until',
            field=django_jalali.db.models.jDateField(blank=True, help_text='این فیلد با ثبت تراکنش\u200cهای اجاره به طور خودکار به صورت روزشمار جلو می\u200cرود. در موارد استثنایی می\u200cتوانید آن را به صورت دستی نیز تغییر دهید.', null=True),
        ),
    ]
