# Generated by Django 5.2.15 on 2026-09-26 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0018_alter_resident_settled_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(blank=True, help_text='حساب کاربری متصل به این ساکن برای ورود به پنل دانشجو.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری سامانه'),
        ),
    ]
