# Generated by Django 5.2.15 on 2026-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0019_resident_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='وضعیت تایید تراکنش (تمام تراکنش\u200cهای ثبت\u200cشده بلافاصله در تسویه لحاظ می\u200cشوند)', verbose_name='تایید شده'),
        ),
    ]
