# Generated by Django 5.2.15 on 2026-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscampaign',
            name='blocked_count',
            field=models.PositiveIntegerField(default=0, verbose_name='مسدود شده (لیست سیاه تبلیغاتی)'),
        ),
        migrations.AlterField(
            model_name='smsrecipientlog',
            name='status',
            field=models.CharField(choices=[('success', 'موفق'), ('blocked_advertising', 'مسدود توسط گیرنده (لیست سیاه تبلیغاتی)'), ('failed', 'ناموفق'), ('skipped_duplicate', 'حذف به دلیل شماره تکراری'), ('skipped_invalid', 'شماره نامعتبر')], max_length=20, verbose_name='وضعیت ارسال'),
        ),
    ]
