# Generated by Django 5.2.15 on 2026-07-28 09:40

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('parent_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('occupation', models.CharField(max_length=20)),
                ('entry_date', django_jalali.db.models.jDateField()),
                ('exit_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('monthly_payment_day', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('original_id', models.IntegerField(help_text='Original resident ID')),
                ('archived_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('dormitory_name', models.CharField(max_length=255)),
                ('room_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Archived Resident',
                'verbose_name_plural': 'Archived Residents',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(max_length=255)),
                ('amount', models.PositiveBigIntegerField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('payment_date', django_jalali.db.models.jDateTimeField()),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('applicable_rent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('dormitory_name', models.CharField(max_length=255)),
                ('original_id', models.IntegerField(help_text='Original transaction ID')),
                ('original_resident_id', models.IntegerField()),
                ('archived_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archived Transaction',
                'verbose_name_plural': 'Archived Transactions',
                'ordering': ['-payment_date'],
            },
        ),
    ]
