# Generated by Django 5.2.15 on 2026-09-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedresident',
            name='is_foreign',
            field=models.BooleanField(default=False, verbose_name='اتباع'),
        ),
        migrations.AlterField(
            model_name='archivedresident',
            name='national_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
