# Generated by Django 5.2.15 on 2026-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archivedresident_is_foreign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedresident',
            name='has_deposit',
            field=models.BooleanField(default=False, verbose_name='ودیعه دارد'),
        ),
        migrations.AddField(
            model_name='archivedresident',
            name='has_lease',
            field=models.BooleanField(default=False, verbose_name='اجاره\u200cنامه دارد'),
        ),
    ]
