# Generated by Django 5.2.15 on 2026-09-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_archivedresident_has_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedresident',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام پدر'),
        ),
    ]
