# Generated by Django 5.2.15 on 2026-09-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_archivedresident_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedresident',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='archived_id_cards/'),
        ),
        migrations.AddField(
            model_name='archivedresident',
            name='id_card_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='archived_id_cards/'),
        ),
        migrations.AddField(
            model_name='archivedresident',
            name='id_card_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='archived_id_cards/'),
        ),
    ]
