"""
AI Daily Log Loader Service
Processes structured JSON generated by LLMs (DeepSeek/ChatGPT) from supervisor voice notes,
matches dormitory entities, validates operations, provides preview, and commits batch updates atomically.
"""

import json
import re
from typing import Dict, Any, List, Optional, Tuple, Union
import jdatetime
from django.db import transaction
from django.utils.html import escape

from apps.dormitory.models import Dormitory, Room, Resident, Transaction, DailyNote
from apps.dormitory.jalali_utils import (
    add_jalali_months,
    format_period_name,
    get_jalali_month_name,
    to_persian_digits,
)


def get_deepseek_prompt_template(ref_date: Optional[jdatetime.date] = None) -> str:
    """
    Generate the complete DeepSeek prompt instruction with today's Jalali date injected.
    """
    if not ref_date:
        ref_date = jdatetime.date.today()

    date_str = f"{ref_date.year:04d}/{ref_date.month:02d}/{ref_date.day:02d}"
    month_name = get_jalali_month_name(ref_date.month)

    return f"""تو یک دستیار هوشمند و حسابدار ارشد برای خوابگاه نوید هستی.
وظیفه تو این است که گزارش صوتی یا متنی روزانه سرپرست خوابگاه را که به زبان محاوره‌ای و عامیانه فارسی است تحلیل کنی و آن را به یک خروجی استاندارد و دقیق در قالب JSON Schema مشخص‌شده تبدیل کنی.

تاریخ مبنای امروز: {date_str} (معادل {ref_date.day} {month_name} {ref_date.year})

قوانین استخراج و تبدیل داده‌ها:
۱. تحلیل تاریخ‌ها:
   - عبارات نسبی مانند «امروز»، «دیروز»، «پریروز»، «فردا» باید دقیقاً به تاریخ شمسی YYYY/MM/DD بر اساس تاریخ مبنا تبدیل شوند.
   - اگر روز و ماه ذکر شد (مثلاً «۵ مهر»)، سال جاری شمسی به آن اضافه شود ({ref_date.year}/07/05).
   - اگر تاریخی برای یک عملیات ذکر نشد، پیش‌فرض همان تاریخ مبنا ({date_str}) است.

۲. تحلیل مبالغ مالی:
   - مبالغ در صحبت‌های عامیانه معمولاً به «تومان» یا «میلیون» هستند.
   - خروجی باید حتماً به عدد صحیح به تومان (amount_tomans) باشد.
   - «۳ تومن» یا «۳ میلیون» = 3000000
   - «دو و نیم میلیون» یا «۲ و ۵۰۰» = 2500000
   - «۸۰۰ تومن» (در بستر اجاره/ودیعه) = 800000

۳. انواع عملیات (action):
   - RENT_PAYMENT: پرداخت اجاره ماهانه
   - DEPOSIT_PAYMENT: پرداخت ودیعه / پول پیش
   - CHECK_OUT: تخلیه اتاق، خروج و تسویه ساکن
   - CHECK_IN: ورود و پذیرش ساکن جدید به خوابگاه
   - ROOM_CHANGE: جابجایی ساکن از یک اتاق به اتاق دیگر
   - MAINTENANCE_NOTE: یادداشت تعمیراتی، خرابی، نظافت یا گزارش انضباطی

۴. روش‌های پرداخت (payment_method):
   - CASH (نقدی)
   - CARD (کارتخوان داخل خوابگاه)
   - BANK_TRANSFER (کارت به کارت، پایا، ساتنا)
   - ONLINE_GATEWAY (درگاه اینترنتی)

۵. فرمت خروجی:
   - خروجی تو باید «صرفاً و منحصراً» یک بلوک کد JSON معتبر باشد (بدون هیچ مقدمه یا توضیح اضافه):

```json
{{
  "report_date": "{date_str}",
  "summary": "خلاصه کوتاه و روان از وقایع گزارش‌شده",
  "events": [
    {{
      "action": "RENT_PAYMENT",
      "resident_name": "نام و نام خانوادگی",
      "room_number": 102,
      "amount_tomans": 3000000,
      "payment_date": "{date_str}",
      "payment_method": "CASH",
      "reference_number": null,
      "description": "توضیحات اختیاری"
    }}
  ]
}}
```"""


def normalize_persian_digits(value: Any) -> str:
    """Convert Persian/Arabic digits to English digits"""
    if value is None:
        return ""
    val_str = str(value)
    persian_digits = "۰۱۲۳۴۵۶۷۸۹"
    arabic_digits = "٠١٢٣٤٥٦٧٨٩"
    english_digits = "0123456789"
    trans_p = str.maketrans(persian_digits, english_digits)
    trans_a = str.maketrans(arabic_digits, english_digits)
    return val_str.translate(trans_p).translate(trans_a)


def normalize_persian_text(text: Optional[str]) -> str:
    """Normalize Persian string for resilient matching"""
    if not text:
        return ""
    # Convert digits first
    text = normalize_persian_digits(text)
    # Arabic letters to Persian
    text = text.replace("ي", "ی").replace("ى", "ی").replace("ك", "ک").replace("ة", "ه").replace("ۀ", "ه")
    text = text.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا")
    # Remove zero-width non-joiner and punctuation
    text = text.replace("\u200c", " ").replace("\u200b", " ")
    text = re.sub(r"[^\w\s]", " ", text)
    # Clean up prefixes/titles
    tokens = text.split()
    cleaned_tokens = [t for t in tokens if t not in ["اقای", "خانم", "سید", "دانشجو", "مهندس"]]
    return " ".join(cleaned_tokens).strip().lower()


def parse_jalali_date(date_val: Any, default_date: Optional[jdatetime.date] = None) -> jdatetime.date:
    """Parse string or date into jdatetime.date safely"""
    if not default_date:
        default_date = jdatetime.date.today()

    if isinstance(date_val, jdatetime.date):
        return date_val

    if not date_val:
        return default_date

    date_str = normalize_persian_digits(str(date_val).strip())
    # Match patterns like YYYY/MM/DD or YYYY-MM-DD
    match = re.search(r"(\d{4})[/\-.](\d{1,2})[/\-.](\d{1,2})", date_str)
    if match:
        year, month, day = int(match.group(1)), int(match.group(2)), int(match.group(3))
        try:
            return jdatetime.date(year, month, day)
        except Exception:
            return default_date

    return default_date


def match_resident(
    resident_name: str,
    room_number: Optional[int] = None,
    dormitory: Optional[Dormitory] = None,
) -> Dict[str, Any]:
    """
    Fuzzy and structured matching of resident in database.
    Returns status: 'EXACT', 'MULTIPLE', 'NOT_FOUND', or 'INACTIVE_MATCH'.
    """
    if not resident_name:
        return {
            "status": "NOT_FOUND",
            "resident": None,
            "candidates": [],
            "message": "نام ساکن در گزارش ذکر نشده است.",
        }

    norm_query = normalize_persian_text(resident_name)
    query_tokens = set(norm_query.split())

    qs = Resident.objects.select_related("room", "dormitory")
    if dormitory:
        qs = qs.filter(dormitory=dormitory)

    # 1. Try matching within the specified room if room_number is given
    if room_number is not None:
        room_residents = qs.filter(room__room_number=room_number, exit_date__isnull=True)
        exact_in_room = []
        partial_in_room = []

        for r in room_residents:
            norm_r = normalize_persian_text(r.full_name)
            r_tokens = set(norm_r.split())
            if norm_query == norm_r:
                exact_in_room.append(r)
            elif query_tokens.issubset(r_tokens) or r_tokens.issubset(query_tokens):
                partial_in_room.append(r)
            elif any(t in r_tokens for t in query_tokens if len(t) > 2):
                partial_in_room.append(r)

        if exact_in_room:
            return {
                "status": "EXACT",
                "resident": exact_in_room[0],
                "candidates": [exact_in_room[0]],
                "message": f"تطبیق قطعی با ساکن اتاق {room_number}.",
            }

        if len(partial_in_room) == 1:
            return {
                "status": "EXACT",
                "resident": partial_in_room[0],
                "candidates": partial_in_room,
                "message": f"تطبیق بر اساس اتاق {room_number} و تشابه نام.",
            }
        elif len(partial_in_room) > 1:
            return {
                "status": "MULTIPLE",
                "resident": None,
                "candidates": partial_in_room,
                "message": f"چند نفر در اتاق {room_number} نام مشابه دارند. لطفاً انتخاب کنید.",
            }

    # 2. Search all active residents in dormitory
    active_residents = qs.filter(exit_date__isnull=True)
    exact_matches = []
    partial_matches = []

    for r in active_residents:
        norm_r = normalize_persian_text(r.full_name)
        r_tokens = set(norm_r.split())
        if norm_query == norm_r:
            exact_matches.append(r)
        elif query_tokens.issubset(r_tokens) or (len(query_tokens) >= 2 and r_tokens.issubset(query_tokens)):
            partial_matches.append(r)
        elif any(t in r_tokens for t in query_tokens if len(t) > 2):
            partial_matches.append(r)

    if len(exact_matches) == 1:
        return {
            "status": "EXACT",
            "resident": exact_matches[0],
            "candidates": exact_matches,
            "message": "تطبیق قطعی نام در کل خوابگاه.",
        }
    elif len(exact_matches) > 1:
        return {
            "status": "MULTIPLE",
            "resident": None,
            "candidates": exact_matches,
            "message": "بیش از یک نفر با این نام دقیق در خوابگاه حضور دارند.",
        }

    if len(partial_matches) == 1:
        return {
            "status": "EXACT",
            "resident": partial_matches[0],
            "candidates": partial_matches,
            "message": "تطبیق بر اساس تشابه نام در خوابگاه.",
        }
    elif len(partial_matches) > 1:
        return {
            "status": "MULTIPLE",
            "resident": None,
            "candidates": partial_matches,
            "message": "چند ساکن با نام مشابه یافت شدند. لطفاً انتخاب کنید.",
        }

    # 3. Check past (left / inactive) residents
    inactive_residents = qs.filter(exit_date__isnull=False)
    for r in inactive_residents:
        norm_r = normalize_persian_text(r.full_name)
        if norm_query == norm_r or query_tokens.issubset(set(norm_r.split())):
            return {
                "status": "INACTIVE_MATCH",
                "resident": r,
                "candidates": [r],
                "message": f"ساکن پیدا شد اما قبلاً در تاریخ {r.exit_date} تسویه کرده و رفته است.",
            }

    return {
        "status": "NOT_FOUND",
        "resident": None,
        "candidates": [],
        "message": f"هیچ ساکنی با نام «{resident_name}» در سیستم یافت نشد.",
    }


def preview_events(
    raw_payload: Union[str, dict],
    supervisor,
    dormitory: Dormitory,
) -> Dict[str, Any]:
    """
    Validates and prepares preview of events from LLM output.
    Does NOT write to database.
    """
    if isinstance(raw_payload, str):
        # Extract json block if wrapped in markdown
        cleaned_str = raw_payload.strip()
        json_match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned_str)
        if json_match:
            cleaned_str = json_match.group(1).strip()
        try:
            data = json.loads(cleaned_str)
        except Exception as e:
            return {
                "success": False,
                "error": f"قالب داده نامعتبر است (خطای JSON): {str(e)}",
                "events": [],
            }
    elif isinstance(raw_payload, dict):
        data = raw_payload
    else:
        return {
            "success": False,
            "error": "داده ارسالی باید شیء JSON یا رشته معتبر باشد.",
            "events": [],
        }

    raw_events = data.get("events", [])
    if not isinstance(raw_events, list):
        return {
            "success": False,
            "error": "فیلد events باید آرایه‌ای از وقایع باشد.",
            "events": [],
        }

    report_date_str = data.get("report_date", "")
    default_date = parse_jalali_date(report_date_str, jdatetime.date.today())

    processed_events = []
    ready_count = 0
    warning_count = 0
    error_count = 0

    valid_methods = [m[0] for m in Transaction.PaymentMethod.choices]

    for idx, ev in enumerate(raw_events):
        action = ev.get("action", "").upper().strip()
        item_id = f"item_{idx}"
        event_date = parse_jalali_date(ev.get("payment_date") or ev.get("exit_date") or ev.get("entry_date") or ev.get("change_date"), default_date)
        event_date_str = f"{event_date.year:04d}/{event_date.month:02d}/{event_date.day:02d}"

        processed_item: Dict[str, Any] = {
            "item_id": item_id,
            "action": action,
            "raw": ev,
            "date": event_date_str,
            "status": "READY",
            "status_label": "آماده ثبت",
            "message": "",
            "resident_id": None,
            "resident_name": ev.get("resident_name") or f"{ev.get('first_name', '')} {ev.get('last_name', '')}".strip(),
            "room_number": ev.get("room_number"),
            "candidates": [],
            "amount_tomans": 0,
            "amount_rials": 0,
            "payment_method": ev.get("payment_method", "CASH").upper().strip(),
            "reference_number": ev.get("reference_number") or "",
            "description": ev.get("description") or ev.get("note") or "",
            "details": {},
        }

        if processed_item["payment_method"] not in valid_methods:
            processed_item["payment_method"] = "CASH"

        # ----------------------------------------------------
        # ACTION: RENT_PAYMENT
        # ----------------------------------------------------
        if action == "RENT_PAYMENT":
            amount_t = ev.get("amount_tomans") or 0
            try:
                amount_t = int(normalize_persian_digits(amount_t))
            except (ValueError, TypeError):
                amount_t = 0

            processed_item["amount_tomans"] = amount_t
            processed_item["amount_rials"] = amount_t * 10

            match = match_resident(
                processed_item["resident_name"],
                processed_item["room_number"],
                dormitory
            )
            processed_item["message"] = match["message"]

            if match["status"] == "EXACT":
                res = match["resident"]
                processed_item["resident_id"] = res.id
                processed_item["resident_name"] = res.full_name
                processed_item["room_number"] = res.room.room_number if res.room else None

                # Calculate projected coverage
                rent_rate = (res.room.monthly_rent if res.room and res.room.monthly_rent else processed_item["amount_rials"])
                months_paid = max(1, round(processed_item["amount_rials"] / rent_rate)) if rent_rate and rent_rate > 0 else 1
                base_date = res.settled_until or res.entry_date or event_date
                proj_end = add_jalali_months(base_date, months_paid)
                period_name = format_period_name(base_date, proj_end)

                processed_item["details"] = {
                    "current_settled_until": str(res.settled_until) if res.settled_until else "ثبت‌نشده",
                    "projected_settled_until": str(proj_end),
                    "period_name": period_name,
                    "room_rent_tomans": (res.room.monthly_rent // 10) if res.room else 0,
                }
                if amount_t <= 0:
                    processed_item["status"] = "ERROR"
                    processed_item["status_label"] = "مبلغ نامعتبر"
                    processed_item["message"] = "مبلغ اجاره باید بیشتر از صفر باشد."
                else:
                    processed_item["status"] = "READY"
                    processed_item["status_label"] = "آماده ثبت"

            elif match["status"] == "MULTIPLE":
                processed_item["status"] = "WARNING"
                processed_item["status_label"] = "نیاز به انتخاب ساکن"
                processed_item["candidates"] = [
                    {
                        "id": c.id,
                        "name": c.full_name,
                        "room": c.room.room_number if c.room else "-",
                        "phone": c.phone_number,
                    }
                    for c in match["candidates"]
                ]
            else:
                processed_item["status"] = "ERROR"
                processed_item["status_label"] = "ساکن یافت نشد"

        # ----------------------------------------------------
        # ACTION: DEPOSIT_PAYMENT
        # ----------------------------------------------------
        elif action == "DEPOSIT_PAYMENT":
            amount_t = ev.get("amount_tomans") or 0
            try:
                amount_t = int(normalize_persian_digits(amount_t))
            except (ValueError, TypeError):
                amount_t = 0

            processed_item["amount_tomans"] = amount_t
            processed_item["amount_rials"] = amount_t * 10

            match = match_resident(
                processed_item["resident_name"],
                processed_item["room_number"],
                dormitory
            )
            processed_item["message"] = match["message"]

            if match["status"] == "EXACT":
                res = match["resident"]
                processed_item["resident_id"] = res.id
                processed_item["resident_name"] = res.full_name
                processed_item["room_number"] = res.room.room_number if res.room else None
                processed_item["status"] = "READY" if amount_t > 0 else "ERROR"
                processed_item["status_label"] = "آماده ثبت" if amount_t > 0 else "مبلغ نامعتبر"
            elif match["status"] == "MULTIPLE":
                processed_item["status"] = "WARNING"
                processed_item["status_label"] = "نیاز به انتخاب ساکن"
                processed_item["candidates"] = [
                    {"id": c.id, "name": c.full_name, "room": c.room.room_number if c.room else "-"}
                    for c in match["candidates"]
                ]
            else:
                processed_item["status"] = "ERROR"
                processed_item["status_label"] = "ساکن یافت نشد"

        # ----------------------------------------------------
        # ACTION: CHECK_OUT
        # ----------------------------------------------------
        elif action == "CHECK_OUT":
            match = match_resident(
                processed_item["resident_name"],
                processed_item["room_number"],
                dormitory
            )
            processed_item["message"] = match["message"]

            if match["status"] == "EXACT":
                res = match["resident"]
                processed_item["resident_id"] = res.id
                processed_item["resident_name"] = res.full_name
                processed_item["room_number"] = res.room.room_number if res.room else None

                if res.exit_date:
                    processed_item["status"] = "WARNING"
                    processed_item["status_label"] = "قبلاً خارج شده"
                    processed_item["message"] = f"این ساکن قبلاً در تاریخ {res.exit_date} خارج شده است."
                else:
                    processed_item["status"] = "READY"
                    processed_item["status_label"] = "آماده خروج"
            elif match["status"] == "MULTIPLE":
                processed_item["status"] = "WARNING"
                processed_item["status_label"] = "نیاز به انتخاب ساکن"
                processed_item["candidates"] = [
                    {"id": c.id, "name": c.full_name, "room": c.room.room_number if c.room else "-"}
                    for c in match["candidates"]
                ]
            else:
                processed_item["status"] = "ERROR"
                processed_item["status_label"] = "ساکن یافت نشد"

        # ----------------------------------------------------
        # ACTION: CHECK_IN (New Resident)
        # ----------------------------------------------------
        elif action == "CHECK_IN":
            first_name = (ev.get("first_name") or "").strip()
            last_name = (ev.get("last_name") or "").strip()
            if not first_name and not last_name and processed_item["resident_name"]:
                parts = processed_item["resident_name"].split(maxsplit=1)
                first_name = parts[0]
                last_name = parts[1] if len(parts) > 1 else "نامشخص"

            room_no = ev.get("room_number")
            room_obj = Room.objects.filter(dormitory=dormitory, room_number=room_no).first() if room_no else None

            deposit_t = ev.get("initial_deposit_tomans") or 0
            rent_t = ev.get("initial_rent_tomans") or 0
            try:
                deposit_t = int(normalize_persian_digits(deposit_t))
                rent_t = int(normalize_persian_digits(rent_t))
            except (ValueError, TypeError):
                pass

            processed_item["details"] = {
                "first_name": first_name,
                "last_name": last_name,
                "phone_number": normalize_persian_digits(ev.get("phone_number") or ""),
                "national_code": normalize_persian_digits(ev.get("national_code") or ""),
                "occupation": ev.get("occupation", "STUDENT"),
                "initial_deposit_tomans": deposit_t,
                "initial_rent_tomans": rent_t,
                "room_found": room_obj is not None,
                "room_capacity": room_obj.capacity if room_obj else 0,
                "room_available": room_obj.available_capacity if room_obj else 0,
            }

            if not room_obj:
                processed_item["status"] = "ERROR"
                processed_item["status_label"] = "اتاق یافت نشد"
                processed_item["message"] = f"اتاق {room_no} در این خوابگاه وجود ندارد."
            elif room_obj.is_full:
                processed_item["status"] = "WARNING"
                processed_item["status_label"] = "اتاق تکمیل است"
                processed_item["message"] = f"اتاق {room_no} در حال حاضر پر است (ظرفیت: {room_obj.capacity})."
            else:
                processed_item["status"] = "READY"
                processed_item["status_label"] = "آماده پذیرش"
                processed_item["message"] = f"اتاق {room_no} دارای {room_obj.available_capacity} تخت خالی است."

        # ----------------------------------------------------
        # ACTION: ROOM_CHANGE
        # ----------------------------------------------------
        elif action == "ROOM_CHANGE":
            new_room_no = ev.get("new_room_number")
            new_room_obj = Room.objects.filter(dormitory=dormitory, room_number=new_room_no).first() if new_room_no else None

            match = match_resident(
                processed_item["resident_name"],
                processed_item["room_number"],
                dormitory
            )
            processed_item["message"] = match["message"]

            if match["status"] == "EXACT":
                res = match["resident"]
                processed_item["resident_id"] = res.id
                processed_item["resident_name"] = res.full_name
                processed_item["room_number"] = res.room.room_number if res.room else None

                if not new_room_obj:
                    processed_item["status"] = "ERROR"
                    processed_item["status_label"] = "اتاق مقصد نامعتبر"
                    processed_item["message"] = f"اتاق مقصد {new_room_no} یافت نشد."
                elif new_room_obj.is_full:
                    processed_item["status"] = "WARNING"
                    processed_item["status_label"] = "اتاق مقصد تکمیل"
                    processed_item["message"] = f"اتاق {new_room_no} پر است."
                else:
                    processed_item["status"] = "READY"
                    processed_item["status_label"] = "آماده انتقال"
                    processed_item["details"] = {
                        "old_room": res.room.room_number if res.room else "-",
                        "new_room": new_room_no,
                    }
            elif match["status"] == "MULTIPLE":
                processed_item["status"] = "WARNING"
                processed_item["status_label"] = "نیاز به انتخاب ساکن"
                processed_item["candidates"] = [
                    {"id": c.id, "name": c.full_name, "room": c.room.room_number if c.room else "-"}
                    for c in match["candidates"]
                ]
            else:
                processed_item["status"] = "ERROR"
                processed_item["status_label"] = "ساکن یافت نشد"

        # ----------------------------------------------------
        # ACTION: MAINTENANCE_NOTE
        # ----------------------------------------------------
        elif action in ["MAINTENANCE_NOTE", "NOTE"]:
            title = ev.get("title") or "گزارش روزانه"
            content = ev.get("content") or ev.get("description") or ev.get("note") or ""
            room_no = ev.get("room_number")
            room_obj = Room.objects.filter(dormitory=dormitory, room_number=room_no).first() if room_no else None

            processed_item["status"] = "READY"
            processed_item["status_label"] = "آماده ثبت"
            processed_item["details"] = {
                "title": title,
                "content": content,
                "room_found": room_obj is not None if room_no else True,
            }
            processed_item["message"] = f"یادداشت برای اتاق {room_no}" if room_no else "یادداشت عمومی خوابگاه"

        else:
            processed_item["status"] = "ERROR"
            processed_item["status_label"] = "نوع عملیات نامعتبر"
            processed_item["message"] = f"عملیات «{action}» در سیستم شناخته‌شده نیست."

        # Aggregate counts
        if processed_item["status"] == "READY":
            ready_count += 1
        elif processed_item["status"] == "WARNING":
            warning_count += 1
        else:
            error_count += 1

        processed_events.append(processed_item)

    return {
        "success": True,
        "report_date": report_date_str or default_date.strftime("%Y/%m/%d"),
        "summary": data.get("summary", "گزارش صوتی خوابگاه"),
        "total_events": len(processed_events),
        "ready_count": ready_count,
        "warning_count": warning_count,
        "error_count": error_count,
        "events": processed_events,
    }


def execute_events(
    events_to_execute: List[Dict[str, Any]],
    supervisor,
    dormitory: Dormitory,
) -> Dict[str, Any]:
    """
    Executes confirmed events inside an atomic transaction.
    Returns details of created/modified records.
    """
    results: List[Dict[str, Any]] = []
    created_transactions = 0
    updated_residents = 0
    created_residents = 0
    created_notes = 0

    with transaction.atomic():
        for ev in events_to_execute:
            action = ev.get("action", "").upper().strip()
            event_date = parse_jalali_date(ev.get("date"), jdatetime.date.today())
            resident_id = ev.get("resident_id")
            description = ev.get("description", "")
            method = ev.get("payment_method", "CASH")
            ref_num = ev.get("reference_number", "")

            # ----------------------------------------------------
            # 1. RENT_PAYMENT
            # ----------------------------------------------------
            if action == "RENT_PAYMENT":
                amount_rials = int(ev.get("amount_rials") or (int(ev.get("amount_tomans", 0)) * 10))
                if not resident_id or amount_rials <= 0:
                    continue

                resident = Resident.objects.select_for_update().get(id=resident_id)
                tx = Transaction(
                    resident=resident,
                    dormitory=dormitory,
                    amount=amount_rials,
                    transaction_type=Transaction.TransactionType.RENT,
                    payment_method=method,
                    payment_date=event_date,
                    reference_number=ref_num,
                    description=description or "ثبت هوشمند از ویس روزانه",
                    is_approved=True,  # Approved directly since supervisor is recording
                    created_by=supervisor,
                )
                tx.save()  # Auto advances settled_until and period_name!
                created_transactions += 1
                results.append({
                    "action": "RENT_PAYMENT",
                    "resident": resident.full_name,
                    "amount_tomans": amount_rials // 10,
                    "period_name": tx.period_name,
                    "settled_until": str(resident.settled_until),
                    "url": f"/admin/dormitory/transaction/{tx.id}/change/",
                })

            # ----------------------------------------------------
            # 2. DEPOSIT_PAYMENT
            # ----------------------------------------------------
            elif action == "DEPOSIT_PAYMENT":
                amount_rials = int(ev.get("amount_rials") or (int(ev.get("amount_tomans", 0)) * 10))
                if not resident_id or amount_rials <= 0:
                    continue

                resident = Resident.objects.get(id=resident_id)
                tx = Transaction(
                    resident=resident,
                    dormitory=dormitory,
                    amount=amount_rials,
                    transaction_type=Transaction.TransactionType.DEPOSIT,
                    payment_method=method,
                    payment_date=event_date,
                    reference_number=ref_num,
                    description=description or "ودیعه - ثبت هوشمند",
                    is_approved=True,
                    created_by=supervisor,
                )
                tx.save()
                created_transactions += 1
                results.append({
                    "action": "DEPOSIT_PAYMENT",
                    "resident": resident.full_name,
                    "amount_tomans": amount_rials // 10,
                    "url": f"/admin/dormitory/transaction/{tx.id}/change/",
                })

            # ----------------------------------------------------
            # 3. CHECK_OUT
            # ----------------------------------------------------
            elif action == "CHECK_OUT":
                if not resident_id:
                    continue
                resident = Resident.objects.select_for_update().get(id=resident_id)
                resident.exit_date = event_date
                resident.status = Resident.Status.LEFT
                resident.save(update_fields=["exit_date", "status"])
                updated_residents += 1
                results.append({
                    "action": "CHECK_OUT",
                    "resident": resident.full_name,
                    "room": resident.room.room_number if resident.room else "-",
                    "exit_date": str(event_date),
                    "url": f"/admin/dormitory/resident/{resident.id}/change/",
                })

            # ----------------------------------------------------
            # 4. CHECK_IN
            # ----------------------------------------------------
            elif action == "CHECK_IN":
                details = ev.get("details", {})
                first_name = details.get("first_name") or ev.get("first_name", "ساکن")
                last_name = details.get("last_name") or ev.get("last_name", "جدید")
                phone = details.get("phone_number") or ev.get("phone_number") or ""
                # If national code or parent phone is not provided, keep as None to flag as incomplete
                nat_code = details.get("national_code") or ev.get("national_code") or None
                parent_phone = details.get("parent_phone_number") or ev.get("parent_phone_number") or None
                room_no = ev.get("room_number")
                room = Room.objects.filter(dormitory=dormitory, room_number=room_no).first() if room_no else None

                # Generate fallback unique phone if completely missing
                if not phone:
                    import random
                    phone = f"09{random.randint(100000000, 999999999)}"

                resident = Resident.objects.create(
                    first_name=first_name,
                    last_name=last_name,
                    national_code=nat_code,
                    phone_number=phone,
                    parent_phone_number=parent_phone,
                    room=room,
                    dormitory=dormitory,
                    entry_date=event_date,
                    occupation=details.get("occupation", "STUDENT"),
                    status=Resident.Status.ACTIVE,
                    registered_by=supervisor,
                )
                created_residents += 1

                # Check if initial rent was paid
                rent_t = details.get("initial_rent_tomans") or 0
                if rent_t > 0:
                    tx_rent = Transaction(
                        resident=resident,
                        dormitory=dormitory,
                        amount=rent_t * 10,
                        transaction_type=Transaction.TransactionType.RENT,
                        payment_method=method,
                        payment_date=event_date,
                        is_approved=True,
                        created_by=supervisor,
                        description="اجاره ماه اول هنگام ثبت‌نام",
                    )
                    tx_rent.save()
                    created_transactions += 1

                # Check if initial deposit was paid
                deposit_t = details.get("initial_deposit_tomans") or 0
                if deposit_t > 0:
                    tx_dep = Transaction(
                        resident=resident,
                        dormitory=dormitory,
                        amount=deposit_t * 10,
                        transaction_type=Transaction.TransactionType.DEPOSIT,
                        payment_method=method,
                        payment_date=event_date,
                        is_approved=True,
                        created_by=supervisor,
                        description="ودیعه هنگام ثبت‌نام",
                    )
                    tx_dep.save()
                    created_transactions += 1

                results.append({
                    "action": "CHECK_IN",
                    "resident": resident.full_name,
                    "room": room.room_number if room else "-",
                    "url": f"/admin/dormitory/resident/{resident.id}/change/",
                })

            # ----------------------------------------------------
            # 5. ROOM_CHANGE
            # ----------------------------------------------------
            elif action == "ROOM_CHANGE":
                if not resident_id:
                    continue
                new_room_no = ev.get("details", {}).get("new_room") or ev.get("new_room_number")
                new_room = Room.objects.filter(dormitory=dormitory, room_number=new_room_no).first()
                if new_room:
                    resident = Resident.objects.select_for_update().get(id=resident_id)
                    old_room_no = resident.room.room_number if resident.room else "-"
                    resident.room = new_room
                    resident.save(update_fields=["room"])
                    updated_residents += 1
                    results.append({
                        "action": "ROOM_CHANGE",
                        "resident": resident.full_name,
                        "old_room": old_room_no,
                        "new_room": new_room.room_number,
                        "url": f"/admin/dormitory/resident/{resident.id}/change/",
                    })

            # ----------------------------------------------------
            # 6. MAINTENANCE_NOTE / NOTE
            # ----------------------------------------------------
            elif action in ["MAINTENANCE_NOTE", "NOTE"]:
                details = ev.get("details", {})
                title = details.get("title") or ev.get("title", "گزارش روزانه")
                content = details.get("content") or ev.get("content") or description
                room_no = ev.get("room_number")
                room = Room.objects.filter(dormitory=dormitory, room_number=room_no).first() if room_no else None

                note = DailyNote.objects.create(
                    dormitory=dormitory,
                    date=event_date,
                    title=title,
                    content=content,
                    note_type=DailyNote.NoteType.MAINTENANCE if action == "MAINTENANCE_NOTE" else DailyNote.NoteType.GENERAL,
                    room=room,
                    created_by=supervisor,
                )
                created_notes += 1
                results.append({
                    "action": "MAINTENANCE_NOTE",
                    "title": title,
                    "room": room.room_number if room else "-",
                    "url": f"/admin/dormitory/dailynote/{note.id}/change/",
                })

    return {
        "success": True,
        "created_transactions": created_transactions,
        "updated_residents": updated_residents,
        "created_residents": created_residents,
        "created_notes": created_notes,
        "total_actions": len(results),
        "results": results,
    }
